# -*- coding: utf-8 -*-
"""EdgeSight — Distributed Edge AI for Environmental Anomaly Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3OR4VeCzokBLLmhDBl_dThg6i_3XQrR
"""

# agents/simulated_sensors.py
import random
import time
from typing import Dict

def generate_env_reading() -> Dict:
    """Simulate a reading from sensors: vibration (0-1), audio_level (dB), temp (C), hum (%)"""
    base_temp = 22.0 + random.uniform(-0.6, 0.6)
    base_hum = 45.0 + random.uniform(-3, 3)
    # occasional anomaly spikes
    if random.random() < 0.02:
        vibration = random.uniform(0.9, 1.2)
        audio = random.uniform(80, 110)  # loud event
    else:
        vibration = random.uniform(0.0, 0.2)
        audio = random.uniform(30, 55)
    return {
        "vibration": round(vibration, 3),
        "audio_db": round(audio, 1),
        "temp_c": round(base_temp, 2),
        "hum_pct": round(base_hum, 1),
        "ts": time.time()
    }